package com.ws101.carpiocebuano.ecommerceapi.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a product category in the e-commerce system.
 *
 * This entity maps to the "categories" table in the database.
 * A category can have multiple products (One-to-Many relationship).
 *
 * Lombok is used to reduce boilerplate code such as
 * getters, setters, and constructors.
 *
 * @author Cebuano, Irene A.
 */
@Entity
@Table(name = "categories")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Category {

    /**
     * Unique identifier of the category.
     * Auto-generated by the database using IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the category.
     * Must be unique and cannot be null.
     */
    @Column(unique = true, nullable = false)
    private String name;

    /**
     * Description of the category.
     * Optional field.
     */
    private String description;

    /**
     * List of products belonging to this category.
     * One-to-Many relationship: One category has many products.
     * mappedBy indicates the field name in the Product entity.
     * CascadeType.ALL means operations cascade to child entities.
     * FetchType.LAZY loads products only when accessed.
     */
    @OneToMany(mappedBy = "category", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<Product> products = new ArrayList<>();

    /**
     * Constructor for creating a category without ID.
     *
     * @param name        category name
     * @param description category description
     */
    public Category(String name, String description) {
        this.name = name;
        this.description = description;
    }
}