package com.ws101.carpiocebuano.ecommerceapi.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a customer order in the e-commerce system.
 *
 * This entity maps to the "orders" table in the database.
 * One order can have multiple order items (One-to-Many relationship).
 *
 * Lombok is used to reduce boilerplate code such as
 * getters, setters, and constructors.
 *
 * @author Carpio, Lyndel J.
 */
@Entity
@Table(name = "orders")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Order {

    /**
     * Unique identifier of the order.
     * Auto-generated by the database using IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the customer who placed the order.
     */
    private String customerName;

    /**
     * Email address of the customer.
     */
    private String customerEmail;

    /**
     * Date and time when the order was placed.
     * Cannot be null.
     */
    @Column(nullable = false)
    private LocalDateTime orderDate;

    /**
     * Total amount of the order.
     */
    private Double totalAmount;

    /**
     * Status of the order.
     * Possible values: PENDING, COMPLETED, CANCELLED
     */
    private String status;

    /**
     * List of order items belonging to this order.
     * One-to-Many relationship: One order has many order items.
     * mappedBy indicates the field name in the OrderItem entity.
     * CascadeType.ALL means operations cascade to child entities.
     * FetchType.LAZY loads order items only when accessed.
     */
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<OrderItem> orderItems = new ArrayList<>();

    /**
     * Constructor for creating an order without ID.
     *
     * @param customerName  name of the customer
     * @param customerEmail email of the customer
     * @param orderDate     date and time of the order
     * @param totalAmount   total amount of the order
     * @param status        status of the order
     */
    public Order(String customerName, String customerEmail, LocalDateTime orderDate, Double totalAmount, String status) {
        this.customerName = customerName;
        this.customerEmail = customerEmail;
        this.orderDate = orderDate;
        this.totalAmount = totalAmount;
        this.status = status;
    }
}