package com.ws101.carpiocebuano.ecommerceapi.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents an individual item within a customer order.
 *
 * This entity maps to the "order_items" table in the database.
 * This is the child entity in both Order and Product relationships.
 *
 * Lombok is used to reduce boilerplate code such as
 * getters, setters, and constructors.
 *
 * @author Carpio, Lyndel J.
 */
@Entity
@Table(name = "order_items")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class OrderItem {

    /**
     * Unique identifier of the order item.
     * Auto-generated by the database using IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Quantity of the product ordered.
     */
    private Integer quantity;

    /**
     * Price of the product at the time of order.
     */
    private Double price;

    /**
     * The order that this item belongs to.
     * Many-to-One relationship: Many order items belong to one order.
     * JoinColumn specifies the foreign key column name.
     */
    @ManyToOne
    @JoinColumn(name = "order_id")
    private Order order;

    /**
     * The product being ordered.
     * Many-to-One relationship: Many order items can reference one product.
     * JoinColumn specifies the foreign key column name.
     */
    @ManyToOne
    @JoinColumn(name = "product_id")
    private Product product;

    /**
     * Constructor for creating an order item without ID.
     *
     * @param quantity quantity of the product
     * @param price    price of the product
     * @param order    the order this item belongs to
     * @param product  the product being ordered
     */
    public OrderItem(Integer quantity, Double price, Order order, Product product) {
        this.quantity = quantity;
        this.price = price;
        this.order = order;
        this.product = product;
    }
}