package com.ws101.carpiocebuano.ecommerceapi.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a product in the e-commerce system.
 *
 * This entity maps to the "products" table in the database.
 * Contains product details such as name, description, price,
 * category, and stock quantity.
 *
 * Lombok is used to reduce boilerplate code such as
 * getters, setters, and constructors.
 *
 * @author Carpio, Lyndel J.
 * @author Cebuano, Irene A.
 */
@Entity
@Table(name = "products")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Product {

    /**
     * Unique identifier of the product.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the product.
     * Cannot be null or empty.
     */
    @NotBlank(message = "Product name is required")
    @Column(nullable = false)
    private String name;

    /**
     * Description of the product.
     */
    private String description;

    /**
     * Price of the product.
     * Must be non-negative.
     */
    @NotNull(message = "Price is required")
    @Min(value = 0, message = "Price must be non-negative")
    @Column(nullable = false)
    private Double price;

    /**
     * Category of the product.
     * Cannot be null or empty.
     */
    @NotBlank(message = "Category is required")
    @Column(nullable = false)
    private String category;

    /**
     * Available stock quantity.
     * Must be non-negative.
     */
    @NotNull(message = "Stock quantity is required")
    @Min(value = 0, message = "Stock must be non-negative")
    private Integer stockQuantity;

    /**
     * Image URL of the product (optional).
     */
    private String imageUrl;
}