package com.ws101.carpiocebuano.ecommerceapi.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import java.util.Collection;
import java.util.List;

/**
 * Represents a user in the e-commerce system.
 *
 * This entity maps to the "users" table in the database.
 * Implements UserDetails to integrate with Spring Security for
 * authentication and authorization purposes.
 *
 * @author Carpio, Lyndel J.
 * @author Cebuano, Irene A.
 */
@Entity
@Table(name = "users")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class User implements UserDetails {

    /**
     * Unique identifier of the user.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Username of the user.
     * Must be unique and cannot be null.
     */
    @Column(unique = true, nullable = false)
    private String username;

    /**
     * Password of the user.
     * Stored as hashed value using BCrypt.
     */
    @Column(nullable = false)
    private String password;

    /**
     * Role of the user.
     * Determines access permissions (e.g., ROLE_USER, ROLE_ADMIN).
     */
    @Column(nullable = false)
    private String role;

    /**
     * Indicates whether the account is enabled.
     */
    private boolean enabled = true;

    /**
     * Indicates whether the account is expired.
     */
    private boolean accountNonExpired = true;

    /**
     * Indicates whether the account is locked.
     */
    private boolean accountNonLocked = true;

    /**
     * Indicates whether the credentials are expired.
     */
    private boolean credentialsNonExpired = true;

    /**
     * Returns the authorities granted to the user.
     * Converts the role string to a GrantedAuthority object.
     *
     * @return collection of GrantedAuthority
     */
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return List.of(new SimpleGrantedAuthority(role));
    }

    /**
     * Returns the password used to authenticate the user.
     *
     * @return the password
     */
    @Override
    public String getPassword() {
        return password;
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return the username
     */
    @Override
    public String getUsername() {
        return username;
    }

    /**
     * Indicates whether the user's account has expired.
     *
     * @return true if the account is non-expired
     */
    @Override
    public boolean isAccountNonExpired() {
        return accountNonExpired;
    }

    /**
     * Indicates whether the user is locked or unlocked.
     *
     * @return true if the account is non-locked
     */
    @Override
    public boolean isAccountNonLocked() {
        return accountNonLocked;
    }

    /**
     * Indicates whether the user's credentials (password) has expired.
     *
     * @return true if the credentials are non-expired
     */
    @Override
    public boolean isCredentialsNonExpired() {
        return credentialsNonExpired;
    }

    /**
     * Indicates whether the user is enabled or disabled.
     *
     * @return true if the user is enabled
     */
    @Override
    public boolean isEnabled() {
        return enabled;
    }
}